apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: user-service
          imagePullPolicy: Never       # <--- added
          ports:
            - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
      nodePort: 30082               # <--- explicit NodePort, change if needed
  type: NodePort
