version: '3.8'

services:
  auth:
    build: ./auth-service
    ports:
      - "5001:5001"

  user:
    build: ./user-service
    ports:
      - "5002:5002"

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
